name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm run test

    - name: Check for vulnerabilities
      run: npm audit

    - name: Merge pull request
      if: success()
      uses: pascalgn/automerge-action@v0.13.1
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        MERGE_LABELS: ""
        MERGE_METHOD: "squash"
        MERGE_COMMIT_MESSAGE: "Automatic merge of successful PR"
        MERGE_FORKS: false
        UPDATE_LABELS: ""